name: Workflow Core for Build Kernel
on:
  workflow_call:
    inputs:
      KERNEL_REPO:
        description: 'Kernel URL repository'
        type: string
      BRANCH:
        description: 'Kernel branch'
        type: string
      DEVICE_TARGET:
        description: 'Device to build'
        type: string
      KSU:
        description: 'Add KernelSU support'
        default: 'NULL'
        type: string
      KSU_BRANCH:
        description: 'KernelSU branch'
        type: string
        default: 'main'
      UPDATE_TOOLCHAIN:
        description: 'Update toolchain cache'
        type: boolean
        default: false
      USE_GCC:
        description: 'Use GCC for compilation instead of LLVM'
        type: boolean
        default: false
      KCFLAGS_W:
        description: 'Enable KCFLAGS=-w'
        type: boolean
        default: false
      EXTRA_CONFIG:
        description: 'Use Extra defconfig'
        type: string
        default: 'NULL'
      NEED_UPLOAD:
        description: 'Upload kernel to Telegram'
        type: boolean
        default: false

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Set Timezone
      run: sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Setup SSH Keys
      if: ${{ startsWith(inputs.KERNEL_REPO, 'git@github.com') && inputs.UPDATE_TOOLCHAIN != 'true' }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone kernel source
      if: inputs.UPDATE_TOOLCHAIN != 'true'
      run: git clone --depth=1 --single-branch -b ${{ inputs.BRANCH }} ${{ inputs.KERNEL_REPO }} kernel_root

    - name: Get Compiler option
      id: curr_compiler
      run: |
        if [[ "${{ inputs.USE_GCC }}" == "true" ]]; then
          echo "tc_dir=$HOME/gcc-arm64" >> $GITHUB_OUTPUT
          echo "cache_key=gcc-eva-arm64" >> $GITHUB_OUTPUT
          echo "active_compiler=gcc" >> $GITHUB_OUTPUT
        else
          echo "tc_dir=$HOME/neutron-clang" >> $GITHUB_OUTPUT
          echo "cache_key=llvm-23-neutron" >> $GITHUB_OUTPUT
          echo "active_compiler=llvm" >> $GITHUB_OUTPUT
        fi

    - name: Cache Toolchain
      id: cache-toolchain
      uses: actions/cache@v5
      with:
        path: ${{ steps.curr_compiler.outputs.tc_dir }}
        key: ${{ steps.curr_compiler.outputs.cache_key }}

    - name: Cache ccache
      uses: actions/cache@v5
      with:
        path: ~/.ccache
        key: ccache-kernel-${{ github.sha }}
        restore-keys: ccache-kernel-

    - name: Prepare Dependencies
      run: chmod +x ./build.sh && bash ./build.sh --setup-deps

    - name: Setup Build Environment
      if: inputs.UPDATE_TOOLCHAIN != 'true'
      id: buildKernel
      run: |
        cd kernel_root
        gitsha1=$(git rev-parse --short HEAD)
        CODENAME=$(cat ../codename)

        echo "buildDetails=$CODENAME-${{ inputs.DEVICE_TARGET }}-$(date +%Y%m%d)_$(echo $gitsha1)-NIGHTLY" >> $GITHUB_OUTPUT
        echo "currDate=$(date)" >> $GITHUB_OUTPUT

    - name: Fetch Toolchains
      if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' || inputs.UPDATE_TOOLCHAIN == 'true' }}
      env:
        UPDATE_TOOLCHAINS: ${{ inputs.UPDATE_TOOLCHAIN }}
        COMP_OPTION: "${{ steps.curr_compiler.outputs.active_compiler }}"
      run: bash ./build.sh --fetch-toolchains

    - name: Build Kernel
      if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      env:
        TG_UPLOAD: ${{ inputs.NEED_UPLOAD }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        DEVICE_TARGET: ${{ inputs.DEVICE_TARGET }}
        CI_ZIPNAME: "${{ steps.buildKernel.outputs.buildDetails }}.zip"
        KCFLAGS_W: "${{ inputs.KCFLAGS_W }}"
        EXTRA_CONFIG: "${{ inputs.EXTRA_CONFIG }}"
        COMP_OPTION: "${{ steps.curr_compiler.outputs.active_compiler }}"
      run: |
        cd kernel_root
        if [ ! -d ~/.ccache ]; then
          mkdir -p ~/.ccache
        fi
        # Handle KernelSU
        if [[ "$KSU" != "NULL" ]]; then
          curl -LSs "${{ inputs.KSU }}" | bash -s ${{ inputs.KSU_BRANCH }}
        fi
        bash ../build.sh

    - name: Upload kernel artifacts
      uses: actions/upload-artifact@v5
      with:
        name: Kernel-${{ steps.buildKernel.outputs.buildDetails }}
        path: |
          kernel_root/out/arch/arm64/boot/Image.gz-dtb
          kernel_root/out/.config
